version = 1

[install]
_1password.pkg-path = "_1password"
_1password.version = "2.30.3"
bun.pkg-path = "bun"
bun.version = "1.2.4"

[hook]
on-activate = '''
  echo "📦 Installing dependencies..."
  bun install --frozen-lockfile

  echo -e "\n🚀 Development Commands"
  echo -e "- Run all tasks\t\t\033[34mbun dev\033[0m"
  echo -e "- Start playground app\t\033[34mbun dev:playground\033[0m"
'''

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
