version = 1

[install]
_1password.pkg-path = "_1password"
_1password.version = "1password-cli-2.30.3"
bun.pkg-path = "bun"
bun.version = "1.1.42"

[hook]
on-activate = '''
  echo "📦 Installing dependencies..."
  bun install --frozen-lockfile
'''

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
